//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto_1._0.PINTAE_Service1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaTramitesCiudadanoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaTramitesPorCedulaJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaTramitePorIdJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTipoTramitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTipoTramitesJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRequisitosPorIdTramiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRequisitosPorIdTramiteJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarTramiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPeticionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPeticionesJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback EntregarDatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNombreCatalogoTipoDatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallProcEntregarDatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiciosPorInstitucionIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Proyecto_1._0.Properties.Settings.Default.Proyecto_1_0_PINTAE_Service1_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaTramitesCiudadanoCompletedEventHandler ConsultaTramitesCiudadanoCompleted;
        
        /// <remarks/>
        public event ConsultaTramitesPorCedulaJsonCompletedEventHandler ConsultaTramitesPorCedulaJsonCompleted;
        
        /// <remarks/>
        public event ConsultaTramitePorIdJsonCompletedEventHandler ConsultaTramitePorIdJsonCompleted;
        
        /// <remarks/>
        public event GetAllTipoTramitesCompletedEventHandler GetAllTipoTramitesCompleted;
        
        /// <remarks/>
        public event GetAllTipoTramitesJsonCompletedEventHandler GetAllTipoTramitesJsonCompleted;
        
        /// <remarks/>
        public event GetRequisitosPorIdTramiteCompletedEventHandler GetRequisitosPorIdTramiteCompleted;
        
        /// <remarks/>
        public event GetRequisitosPorIdTramiteJsonCompletedEventHandler GetRequisitosPorIdTramiteJsonCompleted;
        
        /// <remarks/>
        public event SolicitarTramiteCompletedEventHandler SolicitarTramiteCompleted;
        
        /// <remarks/>
        public event ConsultarPeticionesCompletedEventHandler ConsultarPeticionesCompleted;
        
        /// <remarks/>
        public event ConsultarPeticionesJsonCompletedEventHandler ConsultarPeticionesJsonCompleted;
        
        /// <remarks/>
        public event EntregarDatoCompletedEventHandler EntregarDatoCompleted;
        
        /// <remarks/>
        public event GetNombreCatalogoTipoDatoCompletedEventHandler GetNombreCatalogoTipoDatoCompleted;
        
        /// <remarks/>
        public event CallProcEntregarDatoCompletedEventHandler CallProcEntregarDatoCompleted;
        
        /// <remarks/>
        public event GetServiciosPorInstitucionIdCompletedEventHandler GetServiciosPorInstitucionIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultaTramitesCiudadano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
        public TramiteRealizado[] ConsultaTramitesCiudadano([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cedula) {
            object[] results = this.Invoke("ConsultaTramitesCiudadano", new object[] {
                        cedula});
            return ((TramiteRealizado[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTramitesCiudadanoAsync(string cedula) {
            this.ConsultaTramitesCiudadanoAsync(cedula, null);
        }
        
        /// <remarks/>
        public void ConsultaTramitesCiudadanoAsync(string cedula, object userState) {
            if ((this.ConsultaTramitesCiudadanoOperationCompleted == null)) {
                this.ConsultaTramitesCiudadanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTramitesCiudadanoOperationCompleted);
            }
            this.InvokeAsync("ConsultaTramitesCiudadano", new object[] {
                        cedula}, this.ConsultaTramitesCiudadanoOperationCompleted, userState);
        }
        
        private void OnConsultaTramitesCiudadanoOperationCompleted(object arg) {
            if ((this.ConsultaTramitesCiudadanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTramitesCiudadanoCompleted(this, new ConsultaTramitesCiudadanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultaTramitesPorCedulaJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaTramitesPorCedulaJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cedula) {
            object[] results = this.Invoke("ConsultaTramitesPorCedulaJson", new object[] {
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTramitesPorCedulaJsonAsync(string cedula) {
            this.ConsultaTramitesPorCedulaJsonAsync(cedula, null);
        }
        
        /// <remarks/>
        public void ConsultaTramitesPorCedulaJsonAsync(string cedula, object userState) {
            if ((this.ConsultaTramitesPorCedulaJsonOperationCompleted == null)) {
                this.ConsultaTramitesPorCedulaJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTramitesPorCedulaJsonOperationCompleted);
            }
            this.InvokeAsync("ConsultaTramitesPorCedulaJson", new object[] {
                        cedula}, this.ConsultaTramitesPorCedulaJsonOperationCompleted, userState);
        }
        
        private void OnConsultaTramitesPorCedulaJsonOperationCompleted(object arg) {
            if ((this.ConsultaTramitesPorCedulaJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTramitesPorCedulaJsonCompleted(this, new ConsultaTramitesPorCedulaJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultaTramitePorIdJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaTramitePorIdJson(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("ConsultaTramitePorIdJson", new object[] {
                        id,
                        idSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTramitePorIdJsonAsync(int id, bool idSpecified) {
            this.ConsultaTramitePorIdJsonAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void ConsultaTramitePorIdJsonAsync(int id, bool idSpecified, object userState) {
            if ((this.ConsultaTramitePorIdJsonOperationCompleted == null)) {
                this.ConsultaTramitePorIdJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTramitePorIdJsonOperationCompleted);
            }
            this.InvokeAsync("ConsultaTramitePorIdJson", new object[] {
                        id,
                        idSpecified}, this.ConsultaTramitePorIdJsonOperationCompleted, userState);
        }
        
        private void OnConsultaTramitePorIdJsonOperationCompleted(object arg) {
            if ((this.ConsultaTramitePorIdJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTramitePorIdJsonCompleted(this, new ConsultaTramitePorIdJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetAllTipoTramites", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
        public TipoTramite[] GetAllTipoTramites() {
            object[] results = this.Invoke("GetAllTipoTramites", new object[0]);
            return ((TipoTramite[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTipoTramitesAsync() {
            this.GetAllTipoTramitesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTipoTramitesAsync(object userState) {
            if ((this.GetAllTipoTramitesOperationCompleted == null)) {
                this.GetAllTipoTramitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTipoTramitesOperationCompleted);
            }
            this.InvokeAsync("GetAllTipoTramites", new object[0], this.GetAllTipoTramitesOperationCompleted, userState);
        }
        
        private void OnGetAllTipoTramitesOperationCompleted(object arg) {
            if ((this.GetAllTipoTramitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTipoTramitesCompleted(this, new GetAllTipoTramitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetAllTipoTramitesJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetAllTipoTramitesJson() {
            object[] results = this.Invoke("GetAllTipoTramitesJson", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTipoTramitesJsonAsync() {
            this.GetAllTipoTramitesJsonAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTipoTramitesJsonAsync(object userState) {
            if ((this.GetAllTipoTramitesJsonOperationCompleted == null)) {
                this.GetAllTipoTramitesJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTipoTramitesJsonOperationCompleted);
            }
            this.InvokeAsync("GetAllTipoTramitesJson", new object[0], this.GetAllTipoTramitesJsonOperationCompleted, userState);
        }
        
        private void OnGetAllTipoTramitesJsonOperationCompleted(object arg) {
            if ((this.GetAllTipoTramitesJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTipoTramitesJsonCompleted(this, new GetAllTipoTramitesJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetRequisitosPorIdTramite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
        public TipoDato[] GetRequisitosPorIdTramite(int id_tramite, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tramiteSpecified) {
            object[] results = this.Invoke("GetRequisitosPorIdTramite", new object[] {
                        id_tramite,
                        id_tramiteSpecified});
            return ((TipoDato[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRequisitosPorIdTramiteAsync(int id_tramite, bool id_tramiteSpecified) {
            this.GetRequisitosPorIdTramiteAsync(id_tramite, id_tramiteSpecified, null);
        }
        
        /// <remarks/>
        public void GetRequisitosPorIdTramiteAsync(int id_tramite, bool id_tramiteSpecified, object userState) {
            if ((this.GetRequisitosPorIdTramiteOperationCompleted == null)) {
                this.GetRequisitosPorIdTramiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRequisitosPorIdTramiteOperationCompleted);
            }
            this.InvokeAsync("GetRequisitosPorIdTramite", new object[] {
                        id_tramite,
                        id_tramiteSpecified}, this.GetRequisitosPorIdTramiteOperationCompleted, userState);
        }
        
        private void OnGetRequisitosPorIdTramiteOperationCompleted(object arg) {
            if ((this.GetRequisitosPorIdTramiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRequisitosPorIdTramiteCompleted(this, new GetRequisitosPorIdTramiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetRequisitosPorIdTramiteJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetRequisitosPorIdTramiteJson(int id_tramite, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tramiteSpecified) {
            object[] results = this.Invoke("GetRequisitosPorIdTramiteJson", new object[] {
                        id_tramite,
                        id_tramiteSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRequisitosPorIdTramiteJsonAsync(int id_tramite, bool id_tramiteSpecified) {
            this.GetRequisitosPorIdTramiteJsonAsync(id_tramite, id_tramiteSpecified, null);
        }
        
        /// <remarks/>
        public void GetRequisitosPorIdTramiteJsonAsync(int id_tramite, bool id_tramiteSpecified, object userState) {
            if ((this.GetRequisitosPorIdTramiteJsonOperationCompleted == null)) {
                this.GetRequisitosPorIdTramiteJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRequisitosPorIdTramiteJsonOperationCompleted);
            }
            this.InvokeAsync("GetRequisitosPorIdTramiteJson", new object[] {
                        id_tramite,
                        id_tramiteSpecified}, this.GetRequisitosPorIdTramiteJsonOperationCompleted, userState);
        }
        
        private void OnGetRequisitosPorIdTramiteJsonOperationCompleted(object arg) {
            if ((this.GetRequisitosPorIdTramiteJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRequisitosPorIdTramiteJsonCompleted(this, new GetRequisitosPorIdTramiteJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SolicitarTramite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SolicitarTramite(int id_tramite, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tramiteSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cedula) {
            object[] results = this.Invoke("SolicitarTramite", new object[] {
                        id_tramite,
                        id_tramiteSpecified,
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarTramiteAsync(int id_tramite, bool id_tramiteSpecified, string cedula) {
            this.SolicitarTramiteAsync(id_tramite, id_tramiteSpecified, cedula, null);
        }
        
        /// <remarks/>
        public void SolicitarTramiteAsync(int id_tramite, bool id_tramiteSpecified, string cedula, object userState) {
            if ((this.SolicitarTramiteOperationCompleted == null)) {
                this.SolicitarTramiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarTramiteOperationCompleted);
            }
            this.InvokeAsync("SolicitarTramite", new object[] {
                        id_tramite,
                        id_tramiteSpecified,
                        cedula}, this.SolicitarTramiteOperationCompleted, userState);
        }
        
        private void OnSolicitarTramiteOperationCompleted(object arg) {
            if ((this.SolicitarTramiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarTramiteCompleted(this, new SolicitarTramiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultarPeticiones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
        public Peticion[] ConsultarPeticiones(int id_institucion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_institucionSpecified) {
            object[] results = this.Invoke("ConsultarPeticiones", new object[] {
                        id_institucion,
                        id_institucionSpecified});
            return ((Peticion[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPeticionesAsync(int id_institucion, bool id_institucionSpecified) {
            this.ConsultarPeticionesAsync(id_institucion, id_institucionSpecified, null);
        }
        
        /// <remarks/>
        public void ConsultarPeticionesAsync(int id_institucion, bool id_institucionSpecified, object userState) {
            if ((this.ConsultarPeticionesOperationCompleted == null)) {
                this.ConsultarPeticionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPeticionesOperationCompleted);
            }
            this.InvokeAsync("ConsultarPeticiones", new object[] {
                        id_institucion,
                        id_institucionSpecified}, this.ConsultarPeticionesOperationCompleted, userState);
        }
        
        private void OnConsultarPeticionesOperationCompleted(object arg) {
            if ((this.ConsultarPeticionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPeticionesCompleted(this, new ConsultarPeticionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultarPeticionesJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultarPeticionesJson(int id_institucion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_institucionSpecified) {
            object[] results = this.Invoke("ConsultarPeticionesJson", new object[] {
                        id_institucion,
                        id_institucionSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPeticionesJsonAsync(int id_institucion, bool id_institucionSpecified) {
            this.ConsultarPeticionesJsonAsync(id_institucion, id_institucionSpecified, null);
        }
        
        /// <remarks/>
        public void ConsultarPeticionesJsonAsync(int id_institucion, bool id_institucionSpecified, object userState) {
            if ((this.ConsultarPeticionesJsonOperationCompleted == null)) {
                this.ConsultarPeticionesJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPeticionesJsonOperationCompleted);
            }
            this.InvokeAsync("ConsultarPeticionesJson", new object[] {
                        id_institucion,
                        id_institucionSpecified}, this.ConsultarPeticionesJsonOperationCompleted, userState);
        }
        
        private void OnConsultarPeticionesJsonOperationCompleted(object arg) {
            if ((this.ConsultarPeticionesJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPeticionesJsonCompleted(this, new ConsultarPeticionesJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/EntregarDato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EntregarDato(int id_tipo_dato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tipo_datoSpecified, int id_tramite_solicitado, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tramite_solicitadoSpecified, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] valor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cedula) {
            object[] results = this.Invoke("EntregarDato", new object[] {
                        id_tipo_dato,
                        id_tipo_datoSpecified,
                        id_tramite_solicitado,
                        id_tramite_solicitadoSpecified,
                        valor,
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EntregarDatoAsync(int id_tipo_dato, bool id_tipo_datoSpecified, int id_tramite_solicitado, bool id_tramite_solicitadoSpecified, byte[] valor, string cedula) {
            this.EntregarDatoAsync(id_tipo_dato, id_tipo_datoSpecified, id_tramite_solicitado, id_tramite_solicitadoSpecified, valor, cedula, null);
        }
        
        /// <remarks/>
        public void EntregarDatoAsync(int id_tipo_dato, bool id_tipo_datoSpecified, int id_tramite_solicitado, bool id_tramite_solicitadoSpecified, byte[] valor, string cedula, object userState) {
            if ((this.EntregarDatoOperationCompleted == null)) {
                this.EntregarDatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntregarDatoOperationCompleted);
            }
            this.InvokeAsync("EntregarDato", new object[] {
                        id_tipo_dato,
                        id_tipo_datoSpecified,
                        id_tramite_solicitado,
                        id_tramite_solicitadoSpecified,
                        valor,
                        cedula}, this.EntregarDatoOperationCompleted, userState);
        }
        
        private void OnEntregarDatoOperationCompleted(object arg) {
            if ((this.EntregarDatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EntregarDatoCompleted(this, new EntregarDatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetNombreCatalogoTipoDato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetNombreCatalogoTipoDato(int id_tipo_dato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tipo_datoSpecified) {
            object[] results = this.Invoke("GetNombreCatalogoTipoDato", new object[] {
                        id_tipo_dato,
                        id_tipo_datoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNombreCatalogoTipoDatoAsync(int id_tipo_dato, bool id_tipo_datoSpecified) {
            this.GetNombreCatalogoTipoDatoAsync(id_tipo_dato, id_tipo_datoSpecified, null);
        }
        
        /// <remarks/>
        public void GetNombreCatalogoTipoDatoAsync(int id_tipo_dato, bool id_tipo_datoSpecified, object userState) {
            if ((this.GetNombreCatalogoTipoDatoOperationCompleted == null)) {
                this.GetNombreCatalogoTipoDatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNombreCatalogoTipoDatoOperationCompleted);
            }
            this.InvokeAsync("GetNombreCatalogoTipoDato", new object[] {
                        id_tipo_dato,
                        id_tipo_datoSpecified}, this.GetNombreCatalogoTipoDatoOperationCompleted, userState);
        }
        
        private void OnGetNombreCatalogoTipoDatoOperationCompleted(object arg) {
            if ((this.GetNombreCatalogoTipoDatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNombreCatalogoTipoDatoCompleted(this, new GetNombreCatalogoTipoDatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CallProcEntregarDato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallProcEntregarDato(int id_tipo_dato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tipo_datoSpecified, int id_tramite_solicitado, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_tramite_solicitadoSpecified, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] valor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cedula) {
            object[] results = this.Invoke("CallProcEntregarDato", new object[] {
                        id_tipo_dato,
                        id_tipo_datoSpecified,
                        id_tramite_solicitado,
                        id_tramite_solicitadoSpecified,
                        valor,
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallProcEntregarDatoAsync(int id_tipo_dato, bool id_tipo_datoSpecified, int id_tramite_solicitado, bool id_tramite_solicitadoSpecified, byte[] valor, string cedula) {
            this.CallProcEntregarDatoAsync(id_tipo_dato, id_tipo_datoSpecified, id_tramite_solicitado, id_tramite_solicitadoSpecified, valor, cedula, null);
        }
        
        /// <remarks/>
        public void CallProcEntregarDatoAsync(int id_tipo_dato, bool id_tipo_datoSpecified, int id_tramite_solicitado, bool id_tramite_solicitadoSpecified, byte[] valor, string cedula, object userState) {
            if ((this.CallProcEntregarDatoOperationCompleted == null)) {
                this.CallProcEntregarDatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallProcEntregarDatoOperationCompleted);
            }
            this.InvokeAsync("CallProcEntregarDato", new object[] {
                        id_tipo_dato,
                        id_tipo_datoSpecified,
                        id_tramite_solicitado,
                        id_tramite_solicitadoSpecified,
                        valor,
                        cedula}, this.CallProcEntregarDatoOperationCompleted, userState);
        }
        
        private void OnCallProcEntregarDatoOperationCompleted(object arg) {
            if ((this.CallProcEntregarDatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallProcEntregarDatoCompleted(this, new CallProcEntregarDatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetServiciosPorInstitucionId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetServiciosPorInstitucionId(int id_institucion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_institucionSpecified) {
            object[] results = this.Invoke("GetServiciosPorInstitucionId", new object[] {
                        id_institucion,
                        id_institucionSpecified});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiciosPorInstitucionIdAsync(int id_institucion, bool id_institucionSpecified) {
            this.GetServiciosPorInstitucionIdAsync(id_institucion, id_institucionSpecified, null);
        }
        
        /// <remarks/>
        public void GetServiciosPorInstitucionIdAsync(int id_institucion, bool id_institucionSpecified, object userState) {
            if ((this.GetServiciosPorInstitucionIdOperationCompleted == null)) {
                this.GetServiciosPorInstitucionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiciosPorInstitucionIdOperationCompleted);
            }
            this.InvokeAsync("GetServiciosPorInstitucionId", new object[] {
                        id_institucion,
                        id_institucionSpecified}, this.GetServiciosPorInstitucionIdOperationCompleted, userState);
        }
        
        private void OnGetServiciosPorInstitucionIdOperationCompleted(object arg) {
            if ((this.GetServiciosPorInstitucionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiciosPorInstitucionIdCompleted(this, new GetServiciosPorInstitucionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
    public partial class TramiteRealizado {
        
        private string estadoField;
        
        private string fecha_solicitudField;
        
        private int id_tramiteField;
        
        private bool id_tramiteFieldSpecified;
        
        private string nombre_tramiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fecha_solicitud {
            get {
                return this.fecha_solicitudField;
            }
            set {
                this.fecha_solicitudField = value;
            }
        }
        
        /// <remarks/>
        public int Id_tramite {
            get {
                return this.id_tramiteField;
            }
            set {
                this.id_tramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_tramiteSpecified {
            get {
                return this.id_tramiteFieldSpecified;
            }
            set {
                this.id_tramiteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre_tramite {
            get {
                return this.nombre_tramiteField;
            }
            set {
                this.nombre_tramiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
    public partial class Peticion {
        
        private string cedulaField;
        
        private int id_tipo_datoField;
        
        private bool id_tipo_datoFieldSpecified;
        
        private int id_tramite_solicitadoField;
        
        private bool id_tramite_solicitadoFieldSpecified;
        
        private string nombre_datoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public int Id_tipo_dato {
            get {
                return this.id_tipo_datoField;
            }
            set {
                this.id_tipo_datoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_tipo_datoSpecified {
            get {
                return this.id_tipo_datoFieldSpecified;
            }
            set {
                this.id_tipo_datoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id_tramite_solicitado {
            get {
                return this.id_tramite_solicitadoField;
            }
            set {
                this.id_tramite_solicitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_tramite_solicitadoSpecified {
            get {
                return this.id_tramite_solicitadoFieldSpecified;
            }
            set {
                this.id_tramite_solicitadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre_dato {
            get {
                return this.nombre_datoField;
            }
            set {
                this.nombre_datoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
    public partial class TipoDato {
        
        private string es_obligatorioField;
        
        private string nombre_datoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Es_obligatorio {
            get {
                return this.es_obligatorioField;
            }
            set {
                this.es_obligatorioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre_dato {
            get {
                return this.nombre_datoField;
            }
            set {
                this.nombre_datoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Services_Pintae")]
    public partial class TipoTramite {
        
        private int id_tramiteField;
        
        private bool id_tramiteFieldSpecified;
        
        private string nombre_tramiteField;
        
        /// <remarks/>
        public int Id_tramite {
            get {
                return this.id_tramiteField;
            }
            set {
                this.id_tramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_tramiteSpecified {
            get {
                return this.id_tramiteFieldSpecified;
            }
            set {
                this.id_tramiteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre_tramite {
            get {
                return this.nombre_tramiteField;
            }
            set {
                this.nombre_tramiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultaTramitesCiudadanoCompletedEventHandler(object sender, ConsultaTramitesCiudadanoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTramitesCiudadanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTramitesCiudadanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TramiteRealizado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TramiteRealizado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultaTramitesPorCedulaJsonCompletedEventHandler(object sender, ConsultaTramitesPorCedulaJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTramitesPorCedulaJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTramitesPorCedulaJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultaTramitePorIdJsonCompletedEventHandler(object sender, ConsultaTramitePorIdJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTramitePorIdJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTramitePorIdJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllTipoTramitesCompletedEventHandler(object sender, GetAllTipoTramitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTipoTramitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTipoTramitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoTramite[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoTramite[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllTipoTramitesJsonCompletedEventHandler(object sender, GetAllTipoTramitesJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTipoTramitesJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTipoTramitesJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRequisitosPorIdTramiteCompletedEventHandler(object sender, GetRequisitosPorIdTramiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRequisitosPorIdTramiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRequisitosPorIdTramiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoDato[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoDato[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRequisitosPorIdTramiteJsonCompletedEventHandler(object sender, GetRequisitosPorIdTramiteJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRequisitosPorIdTramiteJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRequisitosPorIdTramiteJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SolicitarTramiteCompletedEventHandler(object sender, SolicitarTramiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarTramiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarTramiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultarPeticionesCompletedEventHandler(object sender, ConsultarPeticionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPeticionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPeticionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Peticion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Peticion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultarPeticionesJsonCompletedEventHandler(object sender, ConsultarPeticionesJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPeticionesJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPeticionesJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EntregarDatoCompletedEventHandler(object sender, EntregarDatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntregarDatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EntregarDatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetNombreCatalogoTipoDatoCompletedEventHandler(object sender, GetNombreCatalogoTipoDatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNombreCatalogoTipoDatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNombreCatalogoTipoDatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CallProcEntregarDatoCompletedEventHandler(object sender, CallProcEntregarDatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallProcEntregarDatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallProcEntregarDatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetServiciosPorInstitucionIdCompletedEventHandler(object sender, GetServiciosPorInstitucionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiciosPorInstitucionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiciosPorInstitucionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591